### ISSUE TITLE
NaN

### ISSUE THREAD

**Issue by redsquare** [rapid7/r7insight_js#19]
Hi -We are using the js sdk and have noticed when viewing the logs the count always says NaN. Not sure where to raise this but found this repo to be as good as any

![image](https://user-images.githubusercontent.com/59662/169332147-931af7c3-1aa3-4359-9f69-55b0f5d2f03d.png)

**Comment by redsquare** [comment]
This happens across all our 100+ logs

**Comment by pquinn-r7** [comment]
Hi @redsquare, sorry this is not within the scope of this library as it is only for sending logs to the Rapid7 insight platform.

Thank you for raising the issue though. This issue is only present in Logentries. It will happen in all cases as the API changed and Logentries does not handle that. InsightOps it shows fine.

For anything related to support issues, you can create a support ticket in logentries in app just for future notice.
![Screen Shot 2022-05-19 at 16 35 43](https://user-images.githubusercontent.com/16612513/169337891-dcd0d4eb-64e4-446f-a9b8-65af918768d9.png)
